pub struct Constants {
    pub color_background: [f32; 4],
    pub color_border: [f32; 4],
    pub color_block: [f32; 4],
    pub color_obstacle: [f32; 4],
    pub color_player1: [f32; 4],
    pub color_player2: [f32; 4],
    pub color_bomb: [f32; 4],
    pub color_fire: [f32; 4],
    pub color_powerup_bomb: [f32; 4],
    pub color_powerup_fire: [f32; 4],
    pub size_x: u32,
    pub size_y: u32,
    pub offset: u8,
}
